apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coinbase
  template:
    metadata:
      labels:
        app: coinbase
    spec:
      containers:
        - name: coinbase-app
          image: your-dockerhub/coinbase-app:latest
          ports:
            - containerPort: 5000

