apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coinbase-service
  template:
    metadata:
      labels:
        app: coinbase-service
    spec:
      containers:
      - name: coinbase-service
        image: isuri2001/coinbase-service
        ports:
        - containerPort: 5000
