apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbase
      color: green
  template:
    metadata:
      labels:
        app: coinbase
        color: green
    spec:
      containers:
        - name: coinbase
          image: isuri001/coinbase-service 
          ports:
            - containerPort: 80
