name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker build -t your-dockerhub/coinbase-app:${{ github.sha }} .
    - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - run: docker push your-dockerhub/coinbase-app:${{ github.sha }}

  deploy-dev:
    needs: build
    steps:
      - run: kubectl apply -f k8s/dev --namespace=dev

  deploy-test:
    needs: deploy-dev
    steps:
      - run: kubectl apply -f k8s/test --namespace=test

  deploy-prod:
    needs: deploy-test
    steps:
      - run: chmod +x scripts/blue-green.sh
      - run: ./scripts/blue-green.sh

